### ISSUE TITLE
Is there any source data for verification?

### ISSUE THREAD

**Issue by black-pigeon** [mkh1992/DVB-T#1]
Hi sir,

This project is very helpful for me to learn DVB-T demodulation, but there isn't any data source reference  when I want to dig into what's inside.

I hope you can upload a data source file that will help me learn the whole demodulation process,  this will be very helpful to me.

**Comment by mhmdkhz92** [comment]
Hi
I appreciate your interest. Unfortunately, I don't have a real-life signal to upload here. Still, I will upload a synthesized signal which I hope will help you start learning. ideally it will be great if you capture a signal from air using an SDR.
Notice: for using this signal, you need to comment out line 23 in logAssessment.m because the signal is already sampled at 64/7 Msps and doesn't need resampling. 

UPDATE: it seems that I cannot upload files larger than 25MB here. I uploaded the file to my OneDrive so you can download it using this link: https://mcmasteru365-my.sharepoint.com/:u:/g/personal/khajezam_mcmaster_ca/ER9lQQJjlVhFo-8tWwlthFgBkIe2HjTh6EtMi0tHQeBuPQ?e=psRDGZ

Best,

**Comment by black-pigeon** [comment]
Hi,
Thanks for your sharing!
I am trying to implement a DVB-T transmitter and receiver on FPGA, your project is very helpful for me to understand the algorithm.

I also found your another project [DVBT-Transmitter](https://github.com/mkh1992/DVBT-Transmitter), if the output data of that project could be used as the source of this one?

**Comment by mhmdkhz92** [comment]
Yes you can use my transmitter code as well and use its output as the input of this one. Actually, I synthesized the file using that code. You can also use the DVB-T project for GnuRadio. it contains all the transmitter and receiver blocks and a few configuration examples for both sides.

**Comment by black-pigeon** [comment]
Thanks for your help, I will close this issue
